apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc-nfs-slow
 annotations:
   volume.beta.kubernetes.io/storage-class: nfs-slow
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 500Mi
