apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-slow
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-slow
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /exports/nfs_slow
    server: ose3-master.example.com
  persistentVolumeReclaimPolicy: Retain
