kind: LDAPSyncConfig
apiVersion: v1
url: ldap://ose3-ldap.example.com
ca: /etc/origin/master/ipa-ca.crt
bindDN: uid=admin,cn=users,cn=accounts,dc=example,dc=com
bindPassword: r3dh4t1!
rfc2307:
  groupsQuery:
    baseDN: cn=groups,cn=accounts,dc=example,dc=com
    derefAliases: never
    filter: '(|(cn=ocp-*)(cn=*app))'
  groupUIDAttribute: dn
  groupNameAttributes:
  - cn
  groupMembershipAttributes:
  - member
  usersQuery:
    baseDN: cn=users,cn=accounts,dc=example,dc=com
    derefAliases: never
  userUIDAttribute: dn
  userNameAttributes:
  - uid
